databases:
  - name: render_example_7_postgresql
    databaseName: render_example_7s
    ipAllowList: []
    plan: free

services:
  - type: web
    name: render_example_7_rails_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exce rails s
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: render_example_7_postgresql
          property: connectionString
  - type: redis
    name: render_example_7_redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction